# Use "--spring.profiles.active=local" para escolher um perfil
server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver

api:
  key: ${GIANT_BOMB_API_KEY}